import 'package:dart_flux/core/server/execution/interface/request_logger_saver.dart';
import 'package:dart_flux/core/server/execution/repo/flux_logger.dart';
import 'package:dart_flux/core/server/routing/models/flux_request.dart';
import 'package:dart_flux/core/server/routing/models/flux_response.dart';
import 'package:dart_flux/core/server/routing/models/http_method.dart';

/// Default implementation of [RequestLoggerSaver] that logs HTTP request and response
/// metadata to the console using [FluxPrintLogger].
///
/// This logger prints the request path, method, response code, and processing duration
/// in milliseconds to help developers monitor server activity.
class FluxRequestLoggerSaver implements RequestLoggerSaver {
  FluxRequestLoggerSaver({
    required this.hitAt,
    required this.leftAt,
    required this.request,
    required this.response,
  });

  /// Timestamp when the request was received.
  @override
  DateTime hitAt;

  /// Timestamp when the response was sent.
  @override
  DateTime leftAt;

  /// The HTTP request object containing details like path, headers, method, etc.
  @override
  FluxRequest request;

  /// The response object generated by the server for the request.
  @override
  FluxResponse response;

  /// Logs the request path, HTTP method, response status code, and processing duration.
  ///
  /// Example log:
  /// ```
  /// /api/user - GET 200 - 12 ms
  /// ```
  @override
  void log() {
    var duration = leftAt.difference(hitAt);
    String path = request.path;
    HttpMethod method = request.method;
    String msg =
        '$path - ${method.name.toUpperCase()} ${response.code} - ${duration.inMilliseconds} ms';

    // Output the log message to the console.
    FluxPrintLogger().rawLog(msg);
  }
}
