name: dart_flux
description: >
  A lightweight and scalable Dart backend framework with built-in 
  web server, authentication, file management, database etc...
version: 0.0.3
homepage: https://github.com/amrmhassan/dart_flux.git

environment:
  sdk: ^3.7.2

dependencies:
  mime: ^2.0.0
  dart_id: ^2.0.2
  logger: ^2.5.0
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  mongo_dart: ^0.10.4
  argon2: ^1.0.1
  dart_jsonwebtoken: ^3.1.1


dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  lints: ^5.0.0
  mockito: ^5.4.5
  mocktail: ^1.0.4
  test: ^1.25.15
  test_cov: ^1.0.1


#  dart run build_runner build --delete-conflicting-outputs
#  dart run build_runner watch --delete-conflicting-outputs