name: dart_flux
description: >
  A lightweight and scalable Dart backend framework with built-in 
  web server, authentication, file management, database etc...
version: 0.0.2
homepage: https://github.com/amrmhassan/dart_flux.git

environment:
  sdk: ^3.7.2

dependencies:
  mime: ^2.0.0
  dart_id: ^2.0.2
  logger: ^2.5.0
  dio: ^5.8.0+1
  # path: ^1.8.0


dev_dependencies:
  build_runner: ^2.4.15
  lints: ^5.0.0
  mockito: ^5.4.5
  mocktail: ^1.0.4
  test: ^1.25.15
  test_cov: ^1.0.1
